// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaGcErIE9LdA7rGq-0zpNbabVChUH52ck',
    appId: '1:113743595266:web:ca83b5be80f0e3b362e41b',
    messagingSenderId: '113743595266',
    projectId: 'login-ea08b',
    authDomain: 'login-ea08b.firebaseapp.com',
    storageBucket: 'login-ea08b.appspot.com',
    measurementId: 'G-YGCCPFEGXG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVdnd4ALegfc3of1iAtqZYWFVtlHvSirQ',
    appId: '1:113743595266:android:0b1eb5e9b09f090962e41b',
    messagingSenderId: '113743595266',
    projectId: 'login-ea08b',
    storageBucket: 'login-ea08b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYKb8-XU3U3vk040V8rGzx9rrvQ1rdLmU',
    appId: '1:113743595266:ios:b2d8db502160f61862e41b',
    messagingSenderId: '113743595266',
    projectId: 'login-ea08b',
    storageBucket: 'login-ea08b.appspot.com',
    iosClientId: '113743595266-tnr8a7tpt1iv4poo18b0pas6jn5uscb8.apps.googleusercontent.com',
    iosBundleId: 'com.example.sigin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYKb8-XU3U3vk040V8rGzx9rrvQ1rdLmU',
    appId: '1:113743595266:ios:52097fd06c93190962e41b',
    messagingSenderId: '113743595266',
    projectId: 'login-ea08b',
    storageBucket: 'login-ea08b.appspot.com',
    iosClientId: '113743595266-sn1788kr48k2u37dokeo66q2ud1g6bq7.apps.googleusercontent.com',
    iosBundleId: 'com.example.sigin.RunnerTests',
  );
}
